services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: search-app
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
    networks:
      - search-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=search-cluster
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - search-network

networks:
  search-network:
    driver: bridge

volumes:
  elasticsearch-data: